In [4]:
import numpy as np
import time

In [3]:
arr=np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
#performance testing
#numpy array stores homegeneous data

size=10_00_000

py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python list time {end-start} seconds")

nd_arr=np.array(py_list)
start=time.time()
np_sq_list=nd_arr**2
end=time.time()
print(f"numpy list time {end-start} seconds")

python list time 0.19945478439331055 seconds
numpy list time 0.006016969680786133 seconds


In [7]:
# memeory

import sys

print(f"python list size = {sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy list size= {nd_arr.nbytes} bytes")

python list size = 8000056000000 bytes
numpy list size= 8000000 bytes


In [19]:

# numpy array creation
arr=np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2) ,arr2.dtype, arr2.shape)

# creating a 2D numpy array
arr2D=np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr2D, arr2D.dtype, arr2D.shape)
print(arr2D**2)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3)
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [41]:
#create

arr1=np.zeros((2,3), dtype="int64")   # filling this numpy array with zeroes
print(arr1, arr1.dtype, arr1.shape)

arr2=np.ones((2,3))
print(arr2, arr2.shape, arr2.dtype)

arr3=np.ones((5,))
print(arr3, arr3.shape)

arr4=np.full((2,3), 100) # prefill with a value
print(arr4, arr4.shape)

arr5=np.eye(3)   # identity matrix
print(arr5, arr5.shape)

#arange(start,end,step)
arr6=np.arange(1,11)       #range element
print(arr6, arr6.shape)

arr7=np.arange(0,11,2)      #between 0 and 11 create elements with 2 steps
print(arr7)

arr8=np.linspace(1,100,4)   # create a array of 4 elements which are equally spaced and between 1,100
print(arr8, arr.shape)

[[0 0 0]
 [0 0 0]] int64 (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64
[1. 1. 1. 1. 1.] (5,)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[ 0  2  4  6  8 10]
[  1.  34.  67. 100.] (5,)


In [47]:
# properties

arr=np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
9
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [51]:
# array reshape and flatten

arr=np.array([ [1,2,3],[4,5,6] ])
print(arr, arr.shape)

new_arr=arr.reshape((3,2))
print(new_arr, new_arr.shape)

f_arr=arr.flatten()
print(f_arr, f_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [57]:
# array indexing

arr=np.array([1,2,3,4,5])
print(arr[4])

arr1=np.array([ [1,2,3] , [4,5,6] ])
print(arr1[1][1])
print(arr1[0][2])

# Fancy indexing
idx=[0,1,3]
print(arr[idx])

# Boolean indexing
print(arr[arr>3])
print(arr[arr>2])
print(arr[arr%2==0])
    

5
5
3
[1 2 4]
[4 5]
[3 4 5]
[2 4]


In [64]:
#slicing

arr=np.array([1,2,3,4,5])
print(arr[1:4])   #[start:end:step]
print(arr[1:])
print(arr[:4])
print(arr[::2])
print(arr[::-1])
print(arr[:len(arr)])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]
[5 4 3 2 1]
[1 2 3 4 5]


In [78]:
# copy of array is created in list while view is created in numpy

# in numpy array changes are made in original array

nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

print("-------------------------")

arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
#sub_arr=arr[1:3].copy()     #if you want to avoid changes in original arr
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
-------------------------
[2 3]
[200   3]
[  1 200   3   4   5]


In [94]:
# data types

arr=np.array([1,2,3,4,5])
print(arr, arr.dtype)  

arr1=np.array([1,2,3,4,5] , dtype="float64")
print(arr1, arr1.dtype)

arr2=np.array([1,2,3,4,5,"hello"])
print(arr2, arr2.dtype)

arr3=np.array([3+5j])    # we use j instead of i
print(arr3, arr3.dtype)

print("----------------------")

com1=np.array([3+5j])
com2=np.array([2+3j])
print(com1+com2)
print(com1-com2)

print("-----------------------")
arr2=np.array([ "prime", {1,2,3}, 3.14 ])     # but it is not advisable to store heterogeneous data in numpy array it is optimized for numerical data
print(arr2, arr2.dtype)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
['1' '2' '3' '4' '5' 'hello'] <U21
[3.+5.j] complex128
----------------------
[5.+8.j]
[1.+2.j]
-----------------------
['prime' {1, 2, 3} 3.14] object


In [7]:
# Multi-dimensional array


import numpy as np
arr2D=np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr2D)
sum=np.sum(arr2D)
print(sum)

sum_of_col=np.sum(arr2D, axis=0)
print("sum of columns:",sum_of_col)

sum_of_row=np.sum(arr2D, axis=1)
print("sum of rows:",sum_of_row)

# slicing
print(arr2D[ 0:2 , 1:2 ])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
sum of columns: [12 15 18]
sum of rows: [ 6 15 24]
[[2]
 [5]]


In [15]:
# 3D array

arr3D=np.array([ [ [1,2] , [3,4] , [5,6] ] , [ [7,8] , [9,10] , [11,12] ] ])    #3D array size 2*3*2
print(arr3D, arr3D.shape)

#indexing

print(arr3D[0,1,1])   # inside first 3*2 we want element 4

print(arr3D[1,1,0])   # inside second 3*2 we want element 9

# slicing
print(arr3D[:,0,0:2])  # first row from both layers

print(arr3D[:, 0:3 ,0])   # first column from both layers

#replacing first row with 99
arr3D[ :,0, 0:2 ] =99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [20]:
# vectoring
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr1**2)
print(arr1+arr2)

print(arr1+5)
print(arr1-arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[ 6  7  8  9 10]
[-5 -5 -5 -5 -5]


In [23]:
# broadcasting

arr1=np.array([1,2,3,4,5])
arr2=np.array([ [1,2,3,4,5] , [1,2,3,4,5] ])
print(arr1.shape, arr2.shape)
print(arr1+arr2)
print(arr1+5)


(5,) (2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
[ 6  7  8  9 10]


In [27]:
# normalization

arr=np.array([ [1,2] , [3,4] ])
mean=np.mean(arr)
print(mean)
std_div=np.std(arr)
print(std_div)

normalized_arr= (arr-mean)/std_div
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [41]:
# mathematical functions

arr=np.array([1,2,3,4,5])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.std(arr))
print(np.var(arr))

[1 2 3 4 5]
15
3.0
3.0
120
1
5
0
4
1.4142135623730951
2.0


In [45]:
# power functions

arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [49]:
# log

arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [65]:
# rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.89))
print(np.trunc(3.14))
arr1=np.array([1,2,3,4,5,3,4,7,8,8])
#arr1=np.array(["aman","aman","raju","shyam","Aman","kiran"])   # ['Aman' 'aman' 'kiran' 'raju' 'shyam']
print(np.unique(arr1))
print(np.sort(arr1))

arr2=np.array([1,-2,5,6,-19])
print(np.sort(arr2))
print(np.abs(arr2))

3.0
4.0
3.0
3.0
[1 2 3 4 5 7 8]
[1 2 3 3 4 4 5 7 8 8]
[-19  -2   1   5   6]
[ 1  2  5  6 19]
